name: Terraform Plan & PR Creation

on:
  push:
    branches:
      - feature/*  # Trigger only for feature branches

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_USER_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_USER_AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: |
          cd tf-example
          terraform init

      - name: Terraform Plan
        run: |
          cd tf-example
          terraform validate
          terraform plan -out=tfplan

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tf-example/tfplan

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Terraform changes - Review required"
          branch: terraform-changes
          title: "Terraform Infrastructure Changes"
          body: "This PR contains Terraform changes that require approval."
          base: main
